# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - segurodehogar

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_112e9449d686403b8a953cb6746d3233 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2bdc860923114eae91ae4f25739901a4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_112e9449d686403b8a953cb6746d3233 }}/azure-app-service/windows/parkingpage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'segurodehogar'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_dadcc183a0cb4a2e8e351a5a87e884d6 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_112e9449d686403b8a953cb6746d3233 }}/azure-app-service/windows/parkingpage:${{ github.sha }}'